language: java
sudo: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - gem install pdd -v 0.20.5
  - gem install xcop -v 0.6
script:
  - set -e
  - pdd --file=/dev/null
# @todo #10:30m Add another check after creating some tests. That will be needed to codecov.
  - ./gradlew buildPlugin
env:
  global:
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
# @todo #10:30m Needs to integrate with codecov. That will enable coverage report for this project.
dist: trusty
